
```{r all-pkgs}
url <- "http://cran.rstudio.com/web/packages/packages.rds"
pkgs <- readRDS(url(url)) %>% 
  as.data.frame() %>%
  rename(package = Package)
```


# Abstract

Data are closely related to social and economic activities in our daily life, so data mining and analysis will definitely benefit us. In many statistical and data analysis tools, we focus on R in this project, and aim to explore the evolution of R packages. By obtaining the daily and recent half year total download count of 17700 R packages (up to 2021-06-07) and R itself, we analyze their pattern characteristics, as well as the relationship between the release date, update times, number of commits on Github, name length and alphabetic order of the packages. Finally, we also check the changes of the top 15 downloaded packages on 1st April from 2013 to 2021, to have a glance of how the user preferences changes to some extent.

\pagebreak

# Introduction {#intro}

Data, which has penetrated into every industry and business field, has become an increasingly important production factor and consumption in our lives. However, data itself must be processed to uncover the information within it. For this reason many statistical tools were born, such as SPSS, Python, R and so on. In this project, we focus on the R language [@R-base].

R is one of the most popular statistical languages and has been ranking competitively even among the general purpose programming languages [peaking 8th in August 2020 in @tiobe]. The TIOBE Programming Community index aggregates several search engines to derive a metric of the popularity of a programming language. It is important to note, however, that programming languages ranked higher than R are mostly general purpose languages and therefore naturally has a larger user base whereas R is exclusively for data analysis and statistical computation alone.  

Today, R is greatly enhanced by over `r comma(length(pkgs$package))` R packages contributed by hundreds of developers all over the world. However, when R originally appeared in August of 1993 with its first official release in June of 1995 [@Ikaha1998], the contributions were managed by only a small group of core developers. In April of 1997, Comprehensive R Archive Network (CRAN) was established as the official R packages repository with 3 mirror sites. Now the source repositories to install R packages have expanded to Bioconductor, Gitlab, GitHub, R-Forge and [106 CRAN mirrors in 49 regions](https://cran.r-project.org/mirmon_report.html). Of all the CRAN mirrors, the daily download count for each package is only readily available from the RStudio CRAN mirror. In this report, we will be focussing only on one CRAN mirror via RStudio, albeit the most popular one, for exploratory data analysis. Henceforth, all download counts of packages refer to the download from this RStudio CRAN mirror. 

The most intuitive embodiment of popularity is the total number of downloads, although it does not directly reflect the number of users, because it includes the repeated downloads by the same user, updates and test downloads caused by the server. Briefly, some works that use these download counts include: the R-package `adjustedcranlogs` [@adjustedcranlogs] attempts to correct this download inflation using a heuristic approach; package `packageRank` [@packageRank] provides a way to compute the rank percentile for packages and filter the invalid downloads including small and medium size logs. What's more, there are also some packages such as `pkgsearch`[@pkgsearch] and `Visualize.CRAN.Downloads`[@Visualize.CRAN.Downloads] providing some visualization methods to explore the package download trend or for convenient searching. More details are explained in Section XX. 


Based on that, researchers have started to study the popularity of R packages from CRAN.  But we still assume in this project that, the download amount is a relatively reliable and simple measure of packages' popularity. Back to the previous studies, the R-package `adjustedcranlogs`[@adjustedcranlogs] finds that there are spike in downloads due to automatic re-downloads and package update, and it also provides a method to remove these download logs.  Some of them are function extensions based on previous packages, and some of them  propose their own new functions, but generally speaking, they are inclined to be more tool like to help users explore the characteristics of package download logs from as many dimensions as possible. 

As for us, the purpose of this project is to explore the download logs of R packages on CRAN and analyze the relationship between some influential factors with it to help users and developers better understand the download amount pattern and also figure out what would determine a package's popularity to some extent. There are some terms involved in this project :

- R language : R is a language and environment for statistical computing and graphics which can be extended easily via packages and provide an Open Source route to participation in statistical methodology. It is available as Free Software under the term of the Free Software Foundation’s GNU General Public License [@gnu].

- R Studio : It is an integrated development environment (IDE) for R. It includes a console, syntax-highlighting editor that supports direct code execution, as well as tools for plotting, history, debugging and workspace management.[@rstudio]

- R Packages : They are collections of functions and data sets developed by the community. They increase the power of R by improving existing base R functionalities, or by adding new ones.

- CRAN : It is a network of ftp and web servers around the world that store identical, up-to-date, versions of code and documentation for R.[@CRAN]

- CRAN mirror : It is a website containing differently located servers, which aims to facilitate people from different regions and countries to access CRAN more smoothly and quickly. And each server is called a mirror.[@cranmirror]

- Github API : It is the abbreviation of Application Programming Interface, which is a software intermediary that allows two applications to talk to each other. 

- CRAN task view : It aims to provide some guidance which packages on CRAN are relevant for tasks related to a certain topic [@crantaskviews].


## Other work 

`adjustedcranlogs`: More specifically, any unusual download spikes are smoothed over and the upward download bias is removed stochastically by subtracting the minimum download count from a random sampling of packages; if this corrected download results in a negative value then this is adjusted to be zero. 
