# Analysis

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(pkgsearch)
library(jsonlite)
library(grid)
```

```{r readcran}
url <- "http://cran.rstudio.com/web/packages/packages.rds"
db <- readRDS(url(url)) %>% 
as.data.frame()

cran2012_10_01 <- read_csv("data/2012-10-01 (1).csv")
cran2013_10_01 <- read_csv("data/2013-10-01.csv")
cran2014_10_01 <- read_csv("data/2014-10-01.csv")
cran2015_10_01 <- read_csv("data/2015-10-01.csv")
cran2016_10_01 <- read_csv("data/2016-10-01.csv")
cran2017_10_01 <- read_csv("data/2017-10-01.csv")
cran2018_10_01 <- read_csv("data/2018-10-01.csv")
cran2019_10_01 <- read_csv("data/2019-10-01.csv")

save(cran2012_10_01, file=here::here("data/cran2012_10_01.rda"))
save(cran2013_10_01, file=here::here("data/cran2013_10_01.rda"))
save(cran2014_10_01, file=here::here("data/cran2014_10_01.rda"))
save(cran2015_10_01, file=here::here("data/cran2015_10_01.rda"))
save(cran2016_10_01, file=here::here("data/cran2016_10_01.rda"))
save(cran2017_10_01, file=here::here("data/cran2017_10_01.rda"))
save(cran2018_10_01, file=here::here("data/cran2018_10_01.rda"))
save(cran2019_10_01, file=here::here("data/cran2019_10_01.rda"))
```

```{r}
# exclude the packages whose author is R studio or from R core group

pkgex_rstu_rcore <- db %>%
  filter(!grepl('RStudio', Author)) %>%
  filter(!grepl('R Core Team', Author)) %>%
  filter(!grepl('Douglas Bates|John Chambers|Peter Dalgaard|Robert Gentleman|Kurt Hornik|Ross Ihaka|Tomas Kalibera|Michael Lawrence|Friedrich Leisch|Uwe Ligges|Thomas Lumley|Martin Maechler|Martin Morgan|Paul Murrell|Brian Ripley|Deepayan Sarkar|Duncan Temple Lang|Luke Tierney|Simon Urbanek|Martyn Plummer', Author))
```

```{r}
# exclude the packages whose author is on the secondary list based on previous step
pkgex_secondary <- pkgex_rstu_rcore %>%
  filter(!grepl('Guido Masarotto|Duncan Murdoch|Henrik Bengtsson|Roger Bivand|Ben Bolker|David Brahm|Vince Carey|Saikat DebRoy|Matt Dowle|Dirk Eddelbuettel|Claus Ekstrom|John Fox|Paul Gilbert|Yu Gong|Gabor Grothendieck|Frank E Harrell Jr|Peter M. Haverty|Torsten Hothorn|Robert King|Kjetil Kjernsmo|Roger Koenker|Philippe Lambert|Jan de Leeuw|Jim Lindsey|Patrick Lindsey|Catherine Loader| Gordon Maclean|Arni Magnusson|John Maindonald|David Meyer|Ei-ji Nakama|Jens Oehlschägel|Steve Oncley|Richard O’Keefe|Hubert Palme|Roger D. Peng|José C. Pinheiro|Tony Plate|Anthony Rossini| Jonathan Rougier|Petr Savicky|Günther Sawitzki|Marc Schwartz|Arun Srinivasan|Detlef Steuer|Bill Simpson|Gordon Smyth|Adrian Trapletti|Terry Therneau|Rolf Turner|Bill Venables|Gregory R. Warnes| Andreas Weingessel|Morten Welinder|James Wettenhall|Simon Wood|and Achim Zeileis', Author))
```



```{r  cran20121001}
cran2012_1001 <- cran2012_10_01 %>%
  drop_na() %>%
  count(package) %>%
  arrange(desc(n)) %>%
  head(15) 
  
cran2012_1001$package <- as.vector(cran2012_1001$package) #get rid of factors

cran2012_1001$package = factor(cran2012_1001$package,cran2012_1001$package)

p1 <- ggplot(data = cran2012_1001) +
  geom_bar(stat="identity", aes(x = package, y = n)) +
  labs(
       title = "Top 15 downloaded packages on 2012-10-01") +
  theme_minimal()  +
  theme(panel.grid.major = element_blank()) +
  theme(
  axis.text=element_text(size=10),
  axis.title=element_text(size=12,face="bold"),
  axis.text.x = element_text(angle = 55, hjust = 1))
```

```{r cran20131001}
cran2013_1001 <- cran2013_10_01 %>%
  drop_na() %>%
  count(package) %>%
  arrange(desc(n)) %>%
  head(15) 
  
cran2013_1001$package <- as.vector(cran2013_1001$package) #get rid of factors

cran2013_1001$package = factor(cran2013_1001$package,cran2013_1001$package)

 p2 <- ggplot(data = cran2013_1001) +
  geom_bar(stat="identity", aes(x = package, y = n)) +
  labs(
       title = "Top 15 downloaded packages on 2013-10-01") +
  theme_minimal()  +
  theme(panel.grid.major = element_blank()) +
  theme(
  axis.text=element_text(size=10),
  axis.title=element_text(size=12,face="bold"),
  axis.text.x = element_text(angle = 55, hjust = 1))
```

```{r cran20141001}
cran2014_1001 <- cran2014_10_01 %>%
  drop_na() %>%
  count(package) %>%
  arrange(desc(n)) %>%
  head(15) 
  
cran2014_1001$package <- as.vector(cran2014_1001$package) #get rid of factors

cran2014_1001$package = factor(cran2014_1001$package,cran2014_1001$package)

p3 <- ggplot(data = cran2014_1001) +
  geom_bar(stat="identity", aes(x = package, y = n)) +
  labs(
       title = "Top 15 downloaded packages on 2014-10-01") +
  theme_minimal()  +
  theme(panel.grid.major = element_blank()) +
  theme(
  axis.text=element_text(size=10),
  axis.title=element_text(size=12,face="bold"),
  axis.text.x = element_text(angle = 55, hjust = 1))
```

```{r cran20151001}
cran2015_1001 <- cran2015_10_01 %>%
  drop_na() %>%
  count(package) %>%
  arrange(desc(n)) %>%
  head(15) 
  
cran2015_1001$package <- as.vector(cran2015_1001$package) #get rid of factors

cran2015_1001$package = factor(cran2015_1001$package,cran2015_1001$package)

p4 <- ggplot(data = cran2015_1001) +
  geom_bar(stat="identity", aes(x = package, y = n)) +
  labs(
       title = "Top 15 downloaded packages on 2015-10-01") +
  theme_minimal()  +
  theme(panel.grid.major = element_blank()) +
  theme(
  axis.text=element_text(size=10),
  axis.title=element_text(size=12,face="bold"),
  axis.text.x = element_text(angle = 55, hjust = 1))
```

```{r cran20161001}
cran2016_1001 <- cran2016_10_01 %>%
  drop_na() %>%
  count(package) %>%
  arrange(desc(n)) %>%
  head(15) 
  
cran2016_1001$package <- as.vector(cran2016_1001$package) #get rid of factors

cran2016_1001$package = factor(cran2016_1001$package,cran2016_1001$package)

p5 <- ggplot(data = cran2016_1001) +
  geom_bar(stat="identity", aes(x = package, y = n)) +
  labs(
       title = "Top 15 downloaded packages on 2016-10-01") +
  theme_minimal()  +
  theme(panel.grid.major = element_blank()) +
  theme(
  axis.text=element_text(size=10),
  axis.title=element_text(size=12,face="bold"),
  axis.text.x = element_text(angle = 55, hjust = 1))
```

```{r cran20171001}
cran2017_1001 <- cran2017_10_01 %>%
  drop_na() %>%
  count(package) %>%
  arrange(desc(n)) %>%
  head(15) 
  
cran2017_1001$package <- as.vector(cran2017_1001$package) #get rid of factors

cran2017_1001$package = factor(cran2017_1001$package,cran2017_1001$package)

p6 <- ggplot(data = cran2017_1001) +
  geom_bar(stat="identity", aes(x = package, y = n)) +
  labs(
       title = "Top 15 downloaded packages on 2017-10-01") +
  theme_minimal()  +
  theme(panel.grid.major = element_blank()) +
  theme(
  axis.text=element_text(size=10),
  axis.title=element_text(size=12,face="bold"),
  axis.text.x = element_text(angle = 55, hjust = 1))
```

```{r cran20181001}
cran2018_1001 <- cran2018_10_01 %>%
  drop_na() %>%
  count(package) %>%
  arrange(desc(n)) %>%
  head(15) 
  
cran2018_1001$package <- as.vector(cran2018_1001$package) #get rid of factors

cran2018_1001$package = factor(cran2018_1001$package,cran2018_1001$package)

p7 <- ggplot(data = cran2018_1001) +
  geom_bar(stat="identity", aes(x = package, y = n)) +
  labs(
       title = "Top 15 downloaded packages on 2018-10-01") +
  theme_minimal()  +
  theme(panel.grid.major = element_blank()) +
  theme(
  axis.text=element_text(size=10),
  axis.title=element_text(size=12,face="bold"),
  axis.text.x = element_text(angle = 55, hjust = 1))
```

```{r cran20191001}
cran2019_1001 <- cran2019_10_01 %>%
  drop_na() %>%
  count(package) %>%
  arrange(desc(n)) %>%
  head(15) 
  
cran2019_1001$package <- as.vector(cran2019_1001$package) #get rid of factors

cran2019_1001$package = factor(cran2019_1001$package,cran2019_1001$package)

p8 <- ggplot(data = cran2019_1001) +
  geom_bar(stat="identity", aes(x = package, y = n)) +
  labs(
       title = "Top 15 downloaded packages on 2019-10-01") +
  theme_minimal()  +
  theme(panel.grid.major = element_blank()) +
  theme(
  axis.text=element_text(size=10),
  axis.title=element_text(size=12,face="bold"),
  axis.text.x = element_text(angle = 55, hjust = 1))
```


```{r compareby2year}
g1 <- ggplotGrob(p1)
g2 <- ggplotGrob(p2)
g12 <- rbind(g1, g2, size = "first")
g12$widths <- unit.pmax(g1$widths, g2$widths)
grid.newpage()
grid.draw(g12)

g3 <- ggplotGrob(p3)
g4 <- ggplotGrob(p4)
g34 <- rbind(g3, g4, size = "first")
g34$widths <- unit.pmax(g3$widths, g4$widths)
grid.newpage()
grid.draw(g34)

g5 <- ggplotGrob(p5)
g6 <- ggplotGrob(p6)
g56 <- rbind(g5, g6, size = "first")
g56$widths <- unit.pmax(g5$widths, g6$widths)
grid.newpage()
grid.draw(g56)

g7 <- ggplotGrob(p7)
g8 <- ggplotGrob(p8)
g78 <- rbind(g7, g8, size = "first")
g78$widths <- unit.pmax(g7$widths, g8$widths)
grid.newpage()
grid.draw(g78)
```

