# Summary

This is the summary about the related literatures. Before that, I would like to introduce some de terms involved in this project.

- R language : R is a language and environment for statistical computing and graphics which can be extended easily via packages and provide an Open Source route to participation in statistical methodology. It is available as Free Software under the term of the Free Software Foundation’s GNU General Public License[@gnu].

- R Studio : It is an integrated development environment (IDE) for R. It includes a console, syntax-highlighting editor that supports direct code execution, as well as tools for plotting, history, debugging and workspace management.

- R Packages : They are collections of functions and data sets developed by the community. They increase the power of R by improving existing base R functionalities, or by adding new ones.

- CRAN : It is a network of ftp and web servers around the world that store identical, up-to-date, versions of code and documentation for R.

- CRAN mirror : It is a website containing differently located servers, which aims to facilitate people from different regions and countries to access CRAN more smoothly and quickly. And each server is called a mirror.


 1. Package "adjustedcranlogs"
 