# Summary

In this project, we collected summary daily download logs of R packages through web API maintained by r-hub[@rhub] and also used daily download data in CRAN for a time period from 2013-04-01 to 2021-04-01 to explore the daily download pattern of all packages both in general and of each year. In that case, we found that it is true that the cumulative number of downloads increases with time, and the variance also increases, which indicates that some packages with larger downloads grow rapidly. In addition, there is also strong weekly seasonality in the daily download plot. The download count will peak through weekdays and drop on weekend, for users may tend to work and study during weekdays while rest on weekends. What's more, through Lorenz curve, we also found that most of the cumulative downloads came from the top 10% downloaded packages, so we could also see that the distribution of downloads is quite unequal. Part of the reason is that these top 10% downloaded packages contain quite a lot popular and frequently used packages, such as `tidyverse` and `rlang`, which would be more probably to gain high downloads. In addition, there are other packages that often get high download volume, which can be divided into the following four categories:

- Packages maintained by R studio
- Packages created by authors from R core group
- Packages created by authors from R secondary group
- Packages created by R related authors
- Packages created by top 20 prolific maintainers (This is resourced at @revolutions)

However, the existence of these packages may make it difficult to reflect the popularity of other packages, we excluded these packages for the analysis of user preferences. And we found that the topic of newly added packages on 1st Oct of each year come from quite different areas, while the packages remaining most stably popular during 2017 to 2019 is about JAVA dependency. Definitely, JAVA always ranked the top three among programming languages according to TIOBE Index[@tiobe], which shows that the number of users under JAVA related packages would be probably huge.

As for R itself, its download pattern is quite similar to that of total R packages on CRAN. And the most used OS for R users is windows OS. Also, the most popular version of R is 3.2.1.

After exploration of the characteristics of download pattern for R package and R itself, we then extracted the release dates of all packages and taskview packages from CRAN to compare the total download count of last half a year among packages with different release date or with different numbers of updates. And we found that for packages from the same topic, earlier release date usually would bring more download count, while packages with more times of updates would not always have higher downloads. So to sum up, packages released earlier and kept updated are more likely to have higher downloads. 

In the next section, we initially tried to scrape the number of commits in Github repository of all packages on CRAN through Github API by R, to check whether more commits would result in more downloads or not. But there came a tricky problem on the rate limit of Github API. As documented in @githubapi, unauthenticated users could only be permitted to send 60 requests per hour. And only after get authentication, could the rate limit be expanded up to 5000 per hour. However, after trying several methods to get authentication, the rate limit was failed increase. So, we switched to make this done with python by setting random agent to avoid the API limit.Meanwhile, in order to display our initial research idea, we still had a look at the last 1% downloaded packages on this question with the original method, and that is also adapted as well. Therefore, we would expect that generally, if a package has more commits on Github repository, it would probably gain more download count.

The last two parts are about analysis for package name. We compared the average downloads among packages with different name length and different alphabetical orders. It is believed that over half of the packages tend to have shorter names probably for the sake of being easily remembered by users. And alphabetical order played little roles in promoting the download volume.


\pagebreak

# Conclusion

In conclusion, we hold the belief that there are many factors that affect the download amount and popularity of the R packages on CRAN, such as the popularity of the creator, the application field of the package, the release date, whether to keep updated, and the length of the name. In addition, we also assume that the number of commits on Github repository will also probably affect the download amount of packages. However, due to technical limitations, the sample size we got is too small to make a strong conclusion on this point. We hope that in the future, we can get over this difficulty and add supplement. Anyway, we could generally believed that a relatively popular package should have earlier release date, shorter name and maybe more commits on Github repository if they have. There is also another point that could not be ignored is to keep updated. 

